# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  certificates_directory: "%kernel.project_dir%/public/uploads/certificates"
  birthCertificate_directory: "%kernel.project_dir%/public/uploads/birthCertificate"
  photos_directory: "%kernel.project_dir%/public/uploads/photos"
  medical_certificates_directory: '%kernel.project_dir%/public/uploads/medical_certificates'
  criminal_records_directory: '%kernel.project_dir%/public/uploads/criminal_records'
  transcripts_directory: '%kernel.project_dir%/public/uploads/transcripts'
  locale: "en"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  # config/services.yaml
  App\Controller\ErrorController:
    public: true
    tags:
      - { name: controller.service_arguments }

  App\EventListener\LocaleListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    # services:
    #     App\Security\CandidateAccessVoter:
    #         tags:
    #             - { name: security.voter }
  App\EventListener\RegistrationFormListener:
    arguments:
      $sessionFactory: '@session.factory'
    tags:
      - { name: kernel.event_subscriber }

  App\EventListener\LoginListener:
    tags:
      - { name: kernel.event_subscriber }
            
  App\EventListener\CandidateFormValidationListener:
    tags:
      - { name: kernel.event_subscriber }
